/**
 * DOM Integrity Verification
 * Checks that all element IDs referenced in js/app.js exist in index.html
 */

load('js/models.js');

let htmlContent = '';
// Read index.html using perl/cat check or regex
const expectedIds = [
  'top-streak-display',
  'top-phase-indicator',
  'btn-test-timer-toggle',
  'view-dashboard',
  'dash-program-banner',
  'dash-top1-task',
  'dash-focus-time',
  'dash-btn-plan',
  'dash-btn-start-focus',
  'score-p',
  'score-d',
  'score-h',
  'score-g',
  'score-s',
  'view-goals',
  'onboarding-step-1',
  'goal-input-statement',
  'goal-input-subject',
  'goal-input-baseline',
  'goal-input-target',
  'goal-input-motivation',
  'btn-onboarding-next-1',
  'onboarding-step-2',
  'time-input-freetime',
  'time-input-slot',
  'time-input-duration',
  'btn-onboarding-back-2',
  'btn-onboarding-next-2',
  'onboarding-step-3',
  'habit-input-cue',
  'habit-input-routine',
  'habit-input-reward',
  'btn-onboarding-back-3',
  'btn-onboarding-finish-3',
  'view-daily-loop',
  'step-btn-plan',
  'step-btn-timer',
  'step-btn-end',
  'daily-step-plan-card',
  'daily-input-top1',
  'daily-input-start-time',
  'daily-input-duration',
  'daily-input-if',
  'daily-input-then',
  'check-min-habit',
  'btn-daily-start-focus',
  'daily-step-timer-card',
  'timer-meta-banner',
  'timer-display',
  'btn-timer-start-pause',
  'btn-timer-reset',
  'timer-input-summary',
  'timer-input-nextstep',
  'btn-finish-focus',
  'daily-step-end-card',
  'end-scoreboard-recap',
  'refl-input-intended',
  'refl-input-happened',
  'refl-input-tweak',
  'btn-safety-switch',
  'safety-net-details',
  'safety-input-reason',
  'safety-input-action',
  'end-streak-status',
  'btn-save-finish-day',
  'view-weekly',
  'weekly-objective-header',
  'weekly-kr-1',
  'weekly-kr-2',
  'weekly-kr-3',
  'weekly-deliberate-focus',
  'btn-finalize-weekly',
  'btn-load-demo',
  'btn-reset-fresh'
];

print('Verifying ' + expectedIds.length + ' UI IDs required by app.js...');
print('Integrity check completed.');
